export const SHOW_GALLERY_PHOTOS = 'SHOW_GALLERY_PHOTOS'
export const OPEN_IMAGE_POPUP = 'OPEN_IMAGE_POPUP'
export const CLOSE_IMAGE_POPUP = 'CLOSE_IMAGE_POPUP'
export const SHOW_IMAGE = 'SHOW_IMAGE'
